import assert from 'node:assert/strict';
import {CacheProbe,ProbePreparationError,syntheticInput,summarizeProbe,exportProbe,probeMarkdown} from '../runtime-src/cache-probe.mjs';
const input={model:'PRIVATE_MODEL',inputBytes:2048,requests:4,accepted:true},requests=[],saved=[];
const makeCall=(i)=>({config:{provider:'desktop-internal',model:input.model,maxTokens:64},async *stream(options){
  requests.push(options);yield {type:'text-delta',text:'PRIVATE_PROVIDER_OUTPUT'};yield {type:'usage',usage:{inputTokens:100,cacheReadTokens:i%2?1000:0,outputTokens:2,totalTokens:i%2?1102:102}};yield {type:'finish',reason:{kind:'stop'}};
}});
const probe=new CacheProbe({prepare:async()=>({calls:Array.from({length:4},(_,i)=>makeCall(i)),configuration:{api:'openai-completions',fingerprint:'a'.repeat(64)}}),pause:async()=>{},persist:async value=>saved.push(value)});
assert.throws(()=>probe.start({...input,accepted:false}));
assert.throws(()=>probe.start({...input,inputBytes:400000}));
assert.throws(()=>probe.start({...input,extra:'anything'}));
probe.start(input);assert.throws(()=>probe.start(input));await probe.done;
const result=probe.snapshot();assert.equal(result.status,'COMPLETED');assert.equal(requests.length,4);assert.equal(saved[0].status,'RUNNING');assert.equal(saved.at(-1).status,'COMPLETED');
assert.equal(requests[0].messages[0].content[0].text,requests[1].messages[0].content[0].text);
assert.equal(requests[0].sessionId,requests[1].sessionId);
assert.notEqual(requests[0].sessionId,requests[2].sessionId);
assert.notEqual(requests[0].messages[0].content[0].text.slice(0,64),requests[2].messages[0].content[0].text.slice(0,64));
for(const r of requests){assert.equal(Buffer.byteLength(r.messages[0].content[0].text),2048);assert(!r.tools);assert.equal(r.maxTokens,64);}
assert.equal(result.summary.positiveReadRequests,2);assert.equal(result.summary.repeatPositiveReadRequests,2);assert.equal(result.summary.rawProviderCounterCoverage,'UNKNOWN');
assert(!JSON.stringify(result).includes('PRIVATE_PROVIDER_OUTPUT'));
assert(!JSON.stringify(exportProbe(result)).includes('PRIVATE'));assert(!probeMarkdown(result).includes('PRIVATE'));
const polluted=structuredClone(result);polluted.rows[0].secret='PRIVATE';polluted.budget.secret='PRIVATE';polluted.summary.note='PRIVATE';polluted.configuration.fingerprint='PRIVATE';
assert(!JSON.stringify(exportProbe(polluted)).includes('PRIVATE'),'exports whitelist even persisted report fields');
assert.equal(summarizeProbe([{repeat:1,usage:{cacheReadTokens:0}},{repeat:2,usage:{cacheReadTokens:null}}]).conclusion,'INCONCLUSIVE');
assert.equal(summarizeProbe([{repeat:1,usage:{cacheReadTokens:0}},{repeat:2,usage:{cacheReadTokens:null}}]).adapterCounterCoverage,1);
assert.notEqual(syntheticInput('run-1','A',2048),syntheticInput('run-2','A',2048));
const refused=new CacheProbe({prepare:async()=>{throw Error('PRIVATE_NETWORK_MESSAGE');}});refused.start(input);await refused.done;assert.equal(refused.snapshot().status,'REFUSED');assert(!JSON.stringify(refused.snapshot()).includes('PRIVATE_NETWORK_MESSAGE'));
const retryRefused=new CacheProbe({prepare:async()=>{throw new ProbePreparationError('RETRIES_ENABLED');}});retryRefused.start(input);await retryRefused.done;assert.match(retryRefused.snapshot().error,/自动重试/);
let firstCall;
const started=new Promise(r=>firstCall=r);
const cancelled=new CacheProbe({pause:async()=>{},prepare:async()=>({calls:Array.from({length:4},()=>({config:{},async *stream(options){firstCall();await new Promise(resolve=>options.signal.addEventListener('abort',resolve,{once:true}));yield {type:'finish',reason:{kind:'aborted'}};}}))})});
const running=cancelled.start(input);await started;cancelled.cancel(running.id);await cancelled.done;assert.equal(cancelled.snapshot().status,'CANCELLED');assert.equal(cancelled.snapshot().rows.length,1,'cancel stops further charged requests');
let deadlineCallback,startedTimeout;
const timeoutStarted=new Promise(r=>startedTimeout=r);
const timed=new CacheProbe({setTimer:fn=>{deadlineCallback=fn;return null;},clearTimer:()=>{},prepare:async()=>({calls:[{config:{},async *stream(options){startedTimeout();await new Promise(resolve=>options.signal.addEventListener('abort',resolve,{once:true}));yield {type:'finish',reason:{kind:'aborted'}};}}]})});
timed.start(input);await timeoutStarted;deadlineCallback();await timed.done;assert.equal(timed.snapshot().status,'TIMEOUT');assert.equal(timed.snapshot().rows.length,1);
let writes=0;
const diskFailure=new CacheProbe({prepare:async()=>({calls:Array.from({length:4},(_,i)=>makeCall(i))}),pause:async()=>{},persist:async()=>{if(++writes>1)throw Error('PRIVATE_DISK_PATH');}});
diskFailure.start(input);await diskFailure.done;assert.equal(diskFailure.snapshot().status,'FAILED');assert.equal(diskFailure.snapshot().rows.length,1,'disk failure stops further calls, does not pretend no requests happened');assert(!JSON.stringify(diskFailure.snapshot()).includes('PRIVATE_DISK_PATH'));
console.log('PASS cache probe: bounded opt-in requests, isolated stable prefixes, no tools/history, cancellation, no output retention, unknown zero counters, export allowlist');
