import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {Gestures,LookDirection} from '../shell-ui/pet/gestures.js';import {Presentation} from '../shell-ui/pet/state.js';import {validateInteractions} from '../shell-ui/pet/interactions.js';
function harness(){let now=0,seq=0;const tasks=new Map(),events=[];const g=new Gestures((...e)=>events.push(e),{now:()=>now,schedule:(f,ms)=>{tasks.set(++seq,{f,at:now+ms});return seq;},cancel:id=>tasks.delete(id)});return{g,events,tick(ms){now+=ms;for(const [id,t]of [...tasks])if(t.at<=now){tasks.delete(id);t.f();}}};}
for(const type of ['mouse','touch','pen'])test(type+' gesture conflict/cancel/long/drag',()=>{
 const h=harness(),p={id:1,x:30,y:40,type,button:0};h.g.down(p);h.g.up(p);h.tick(100);h.g.down(p);h.g.up(p);h.tick(400);assert.deepEqual(h.events.map(e=>e[0]),['double']);
 h.g.down(p);h.tick(650);h.g.up(p);h.tick(400);assert.equal(h.events.at(-1)[0],'long');
 h.g.down(p);h.g.move({...p,x:39});h.tick(1000);h.g.up(p);assert.deepEqual(h.events.slice(-2).map(e=>e[0]),['drag','drag-end']);
 const n=h.events.length;h.g.down(p);h.g.reset();h.tick(1000);assert.equal(h.events.length,n);
 h.g.down(p);h.g.down({...p,id:2});h.tick(1000);assert.equal(h.events.length,n);
});
test('16 directions, center neutral and boundary debounce',()=>{let now=0;const l=new LookDirection(()=>now);for(let i=0;i<16;i++){now+=100;const a=i*22.5*Math.PI/180;assert.deepEqual(l.update(Math.sin(a)*80,-Math.cos(a)*80),{row:9+Math.floor(i/8),column:i%8});}assert.deepEqual(l.update(0,0),{row:0,column:6});now+=100;l.update(0,-80);now+=10;assert.deepEqual(l.update(80,0),{row:9,column:0});});
test('drag reaction preserves wait, event beats interaction, bounded cooldown',()=>{let now=0;const m=new Presentation(()=>now);m.accept({generation:'g',revision:1,items:[{sessionId:'a',status:'WAITING_INPUT',revision:1,at:0}]});m.drag='dragged';m.interact('pat');assert.equal(m.animation(),'dragged');assert.equal(m.bubble(),'等待你的输入');m.drag=null;m.reaction=null;assert.equal(m.animation(),'waiting');m.reaction={id:'failed',kind:'task'};m.interact('happy');assert.equal(m.animation(),'failed');});
test('extension frames/durations/crops are explicit and untrusted triggers rejected',async()=>{const v=JSON.parse(await readFile(new URL('../assets/pets/xiaojing/extensions/interactions.json',import.meta.url)));const d={'pat.webp':[768,208],'happy.webp':[768,208],'dragged.webp':[576,208]};assert.equal(validateInteractions(v,d),v);assert.throws(()=>validateInteractions({...v,schemaVersion:9},d));assert.throws(()=>validateInteractions({...v,triggers:{execute:'pat'}},d));const bad=structuredClone(v);bad.animations[0].frames[0].column=99;assert.throws(()=>validateInteractions(bad,d));});
