import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,readdirSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {createRequire} from 'node:module';
import {synchronizeDesktopSettings} from '../runtime-src/settings-sync.mjs';
const runtimeRoot=resolve('runtime');
const require=createRequire(join(runtimeRoot,'dsh/package.json'));
const {parse,stringify}=require('yaml');
mkdirSync('.build',{recursive:true});
const home=mkdtempSync(resolve('.build/settings-sync-'));
const patchFile=join(home,'desktop.patch.json');
const file=join(home,'settings.yaml');
const provider={api:'openai-completions',apiKeyEnv:'DSH_DESKTOP_LLM_KEY',baseURL:'http://localhost/v1',models:[{id:'glm-5.3',contextWindow:1000000,maxTokens:128000},{id:'glm-5.3-flash',contextWindow:1000000,maxTokens:128000}]};
const patch=[{id:'llm-pi-ai',config:{providers:{'desktop-internal':provider}}},{id:'agent-default-model',config:{provider:'desktop-internal',model:'glm-5.3'}}];
writeFileSync(patchFile,JSON.stringify(patch));
const old='# Keep my preferences\n'+stringify({'llm-pi-ai':{providers:{'desktop-internal':{models:[{id:'glm-5.3[1m]',contextWindow:32768,maxTokens:4096}]},other:{apiKeyEnv:'OTHER_TEST_KEY',models:[{id:'other'}]}}},'agent-default-model':{provider:'desktop-internal',model:'glm-5.3[1m]'},'ui-theme':{mode:'light'}});
writeFileSync(file,old);
const sync=()=>synchronizeDesktopSettings({home,patchFile,runtimeRoot});
await sync();
let current=parse(readFileSync(file,'utf8'));
assert.deepEqual(current['llm-pi-ai'].providers['desktop-internal'],provider);
assert.deepEqual(current['llm-pi-ai'].providers.other,parse(old)['llm-pi-ai'].providers.other);
assert.equal(current['ui-theme'].mode,'light');
assert(readFileSync(file,'utf8').includes('# Keep my preferences'));
assert.equal(current['agent-default-model'].model,'glm-5.3');
assert.equal(readFileSync(join(home,'desktop-settings-backups',readdirSync(join(home,'desktop-settings-backups'))[0]),'utf8'),old);
current['agent-default-model'].model='glm-5.3-flash';writeFileSync(file,stringify(current));
await sync();assert.equal(parse(readFileSync(file,'utf8'))['agent-default-model'].model,'glm-5.3-flash','unchanged config preserves a valid native selection');
const before=readFileSync(file,'utf8');await sync();assert.equal(readFileSync(file,'utf8'),before,'idempotent');
patch[1].config.model='glm-5.3-flash';provider.models[1].maxTokens=64000;writeFileSync(patchFile,JSON.stringify(patch));
current['agent-default-model'].model='glm-5.3';writeFileSync(file,stringify(current));
await sync();assert.equal(parse(readFileSync(file,'utf8'))['agent-default-model'].model,'glm-5.3-flash','changed desktop config wins over native default');
current=parse(readFileSync(file,'utf8'));current['agent-default-model'].reasoningEffort='high';writeFileSync(file,stringify(current));
provider.models[1].maxTokens=128000;writeFileSync(patchFile,JSON.stringify(patch));
await sync();assert.equal(parse(readFileSync(file,'utf8'))['agent-default-model'].reasoningEffort,'high','capacity changes preserve native effort for the same model');
for(const bad of ['bad: [','- not-a-map','llm-pi-ai: bad']){
 writeFileSync(file,bad);await assert.rejects(sync());assert.equal(readFileSync(file,'utf8'),bad);
}
console.log('PASS native settings synchronization: stale overrides, default selection, unrelated settings/comments, backup, idempotence, malformed input preservation');
