export const artifactsHtml=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DSHDesktop · 文件与产物</title><link rel="stylesheet" href="/desktop-diagnostics/theme.css"><style>main{max-width:1150px;margin:auto;padding:28px}header,.actions{display:flex;gap:12px;align-items:center;flex-wrap:wrap}header{justify-content:space-between}section{padding:18px;margin:16px 0;border:1px solid var(--dsw-alias-border-l2);border-radius:12px}input{min-width:240px;flex:1}button,a.button{padding:8px 12px;text-decoration:none}h2{font-size:18px}#notice{min-height:24px}.path{overflow-wrap:anywhere;font-family:Consolas,monospace}.metadata{margin:8px 0}#files{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:16px}#files section{margin:0}.error{color:var(--dsw-alias-state-error-primary)}</style><script src="/desktop-diagnostics/theme.js" defer></script><script src="/desktop-diagnostics/artifacts.js" defer></script></head><body><main><header><h1>文件与产物</h1><a class="button" href="/desktop-diagnostics">会话诊断</a></header><p>打开报告、定位输出文件或另存一份。文件操作仅在你点击时发生，不会发送给模型。</p><section><div class="actions"><label for="workspace">工作区</label><input id="workspace" placeholder="工作区绝对路径"><button id="load">读取文件列表</button></div><p id="context"></p><div class="actions"><label for="path">添加文件</label><input id="path" placeholder="如 reports/result.csv"><button id="register" disabled>添加已有文件</button></div><p>构建产物来自项目操作的 artifacts 配置；日志自动列出。会话入口另包含 DSH 正式交付的文件。列表指向当前文件，不保证由该次操作新建，也不是内容快照。</p></section><p id="notice" role="status"></p><div id="files"></div><p>文件改变后请刷新；入口 10 分钟内有效。可执行文件、脚本及其他未开放的类型仅支持定位和另存，避免点击「打开」直接执行。另存上限 512 MiB；更大文件可用文件管理器复制。</p></main></body></html>`;
export const artifactsScript=String.raw`
'use strict';const $=id=>document.getElementById(id);let workspace='',session=new URLSearchParams(location.search).get('sessionId')??new URLSearchParams(location.search).get('session'),busy=false;
function element(tag,text){const e=document.createElement(tag);e.textContent=text;return e;}
function state(value){busy=value;for(const id of ['load','register','workspace','path'])$(id).disabled=value;for(const button of $('files').querySelectorAll('button'))button.disabled=value||button.dataset.blocked==='true';}
async function api(path,data){const response=await fetch('/desktop-diagnostics/api/artifacts/'+path,data===undefined?{}:{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});const value=await response.json();if(!response.ok)throw Error(value.error);return value;}
const names={'session':'会话交付','manual':'手动登记','action':'构建声明','action-log':'操作日志'};
async function load(reset=false){if(busy)return;state(true);$('notice').textContent='读取本地文件…';try{if(reset){workspace=$('workspace').value.trim();session=null;}const query=new URLSearchParams({workspace});if(session)query.set('session',session);const value=await api('list?'+query);workspace=value.workspace;$('workspace').value=workspace;$('context').textContent=session?'当前会话与工作区的文件。':'当前工作区的登记文件与最近项目操作。';$('files').replaceChildren(...value.items.map(row=>{const section=element('section','');section.append(element('h2',row.name??row.path),element('p',row.path));section.lastChild.className='path';section.append(element('p',(names[row.source]??row.source)+(row.label?' · '+row.label:'')+(row.status?' · '+row.status:'')));if(!row.available){section.append(element('p',row.message??'文件不可用'));return section;}section.append(element('p',new Intl.NumberFormat().format(row.size)+' bytes · '+new Date(row.modifiedAt).toLocaleString()));const bar=element('div','');bar.className='actions';for(const [action,title] of [['open','打开'],['reveal','所在目录']]){const button=element('button',title);button.dataset.blocked=String(action==='open'&&!row.canOpen);button.disabled=button.dataset.blocked==='true';button.onclick=async()=>{if(busy)return;state(true);try{await api('action',{id:row.id,action});$('notice').textContent='已交给本机应用处理。';}catch(error){$('notice').textContent=error.message;}finally{state(false);}};bar.append(button);}if(row.canSave){const link=element('a','另存为');link.className='button';link.href='/desktop-diagnostics/api/export?artifact='+encodeURIComponent(row.id);link.setAttribute('download',row.name);bar.append(link);}section.append(bar);return section;}));$('notice').textContent=value.items.length?'已读取 '+value.items.length+' 条记录。'+(value.truncated?' 会话仅显示最近 100 个交付文件。':''):'暂无登记文件。可添加工作区文件，或在项目操作中配置 artifacts。';}
catch(error){$('notice').textContent=error.message;$('files').replaceChildren();}finally{state(false);$('register').disabled=!workspace;}}
$('load').onclick=()=>load(true);$('register').onclick=async()=>{if(busy||!workspace)return;state(true);try{await api('register',{workspace,path:$('path').value.trim().replaceAll('\\','/')});$('path').value='';}catch(error){$('notice').textContent=error.message;state(false);return;}state(false);await load();};
$('workspace').value=new URLSearchParams(location.search).get('workspace')??'';workspace=$('workspace').value;if(workspace||session)load();
`;
