export const cacheHtml=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DSHDesktop · 缓存验证</title><link rel="stylesheet" href="/desktop-diagnostics/theme.css"><style>main{max-width:1120px;margin:auto;padding:28px}header,.actions{display:flex;align-items:center;gap:12px;flex-wrap:wrap}header{justify-content:space-between}section{padding:20px;border:1px solid var(--dsw-alias-border-l2);border-radius:12px;margin:20px 0}label{display:flex;gap:10px;align-items:center;margin:10px 0}table{width:100%;border-collapse:collapse}td,th{padding:10px;text-align:left;border-bottom:1px solid var(--dsw-alias-border-l2)}pre{white-space:pre-wrap;overflow-wrap:anywhere}button,a.button{padding:8px 12px;text-decoration:none}.scroll{overflow:auto}#notice{min-height:24px}h2{font-size:18px}input[type=checkbox]{width:auto}</style><script src="/desktop-diagnostics/theme.js" defer></script><script src="/desktop-diagnostics/cache.js" defer></script></head><body><main>
<header><h1>缓存验证</h1><div class="actions"><a class="button" href="/desktop-diagnostics">会话诊断</a><button id="refresh">刷新配置</button></div></header>
<p>为当前连接验证合成请求的缓存返回值。读取本页不发送模型请求；点击开始后使用当前连接的凭据、代理、CA 和原生适配器。</p><p id="notice" role="status"></p>
<section><h2>服务能力声明</h2><label>模型<select id="model"></select></label><p>按服务文档或管理员提供的信息填写。声明与探针结果分开记录，保存声明不会自动启用请求字段或修改模型配置。</p><div id="capabilities"></div><div class="actions"><button id="save-capabilities">保存声明</button><span id="capability-source"></span></div></section>
<section><h2>当前适配器行为</h2><pre id="adapter"></pre><p>参数随连接配置保存、切换后应用。独立缓存键、cache_control 与保留时间受适配器接口约束；不把未知网关自动视为支持。</p></section>
<section><h2>运行合成探针</h2><p>A、B 两组使用不同随机前缀，每组重复相同内容，用于观察重复请求。两组使用相同配置；本次结果不代表不同参数之间的 A/B 效果。</p>
<label>每次输入长度<select id="bytes"><option value="2048">2 KiB</option><option value="8192" selected>8 KiB</option><option value="32768">32 KiB</option></select></label><label>请求数<select id="requests"><option value="4">4 次 · 每组重复 2 次</option><option value="6">6 次 · 每组重复 3 次</option></select></label>
<p id="budget"></p><p>仅发送合成文本，不加载工程、规则、Skills 或真实历史。每次请求 maxTokens=64，总时限 120 秒，不自动重试，不执行模型返回的工具。计费和硬限额最终由服务端决定。</p><label><input id="accept" type="checkbox">我确认将按上述预算向当前连接发送合成请求，可能产生模型费用。</label><div class="actions"><button id="start" disabled>开始探针</button><button id="cancel" disabled>取消当前探针</button></div></section>
<section><h2>探针结果</h2><div class="actions"><select id="history"><option value="">当前探针</option></select><a id="json" class="button" hidden>导出 JSON</a><a id="md" class="button" hidden>导出 Markdown</a></div><p id="summary">尚未运行。</p><div class="scroll"><table><thead><tr><th>组 / 重复</th><th>状态</th><th>缓存读取</th><th>首输出</th><th>总耗时</th></tr></thead><tbody id="rows"></tbody></table></div><p id="report-warning"></p><small>计数来源为 DSH 适配层，原始服务计数覆盖未知。零值可能来自未命中或适配层补零；耗时下降也不能单独证明缓存命中。结果按连接保留最近 30 份。导出不含模型名、地址、会话或正文。</small></section>
</main></body></html>`;
export const cacheScript=String.raw`
'use strict';
const $=id=>document.getElementById(id),names={automaticCaching:'自动前缀缓存',promptCacheKey:'显式缓存键',cacheControl:'显式缓存标记',longRetention:'长期保留参数'};
let current=null,config=null,busy=false,polling=false,loaded=false,lastStatus='',selectedReport=null,formFingerprint=null,mutation=0;
const status={RUNNING:'运行中',COMPLETED:'已完成',FAILED:'失败',REFUSED:'未执行',TIMEOUT:'超时',CANCELLED:'已取消',UNKNOWN:'未知',INTERRUPTED:'引擎中断',OUTPUT_LIMIT:'达到输出上限',UNEXPECTED_TOOL_CALL:'意外工具请求（未执行）'};
const text=(tag,value)=>{const e=document.createElement(tag);e.textContent=value;return e;};
async function api(path,value){const response=await fetch('/desktop-diagnostics/api/cache/'+path,value===undefined?{}:{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(value)});const data=await response.json();if(!response.ok)throw Error(data.error||'请求失败');return data;}
function controls(){const running=current?.status==='RUNNING';$('start').disabled=busy||running||!$('accept').checked||!$('model').value;$('cancel').disabled=busy||!running;for(const id of ['model','bytes','requests'])$(id).disabled=busy||running;$('save-capabilities').disabled=busy||!config||!$('model').value;}
function budget(){const bytes=Number($('bytes').value),requests=Number($('requests').value);$('budget').textContent='本次最多 '+requests+' 次请求，合计 '+(bytes*requests/1024)+' KiB 合成输入，每次最多请求 64 个输出 tokens。';}
function capabilities(){formFingerprint=config?.fingerprint;const saved=config?.capabilities[$('model').value];for(const key of Object.keys(names))$(key).value=saved?.features[key]??'unknown';$('capability-source').textContent=saved?.source==='user-declared'?(saved.stale?'声明对应旧配置，请重新核对。':'来源：用户声明，尚非服务端证实。'):'来源：未知';}
function report(value){selectedReport=value;$('rows').replaceChildren();for(const row of value?.rows??[]){const tr=document.createElement('tr');for(const v of [row.group+' / '+row.repeat,status[row.status]??'未知',row.usage.cacheReadTokens??'未知',row.firstOutputMs===null?'未知':Math.round(row.firstOutputMs)+' ms',row.durationMs===null?'—':Math.round(row.durationMs)+' ms'])tr.append(text('td',v));$('rows').append(tr);}
 $('summary').textContent=value?(status[value.status]??'未知')+' · 已完成/开始 '+value.rows.length+'/'+value.budget.requests+' 次 · '+(value.summary.positiveReadRequests?'适配层报告了缓存读取（'+value.summary.positiveReadRequests+' 次）':'当前结果不足以确认缓存是否生效')+' · 适配层计数覆盖 '+value.summary.adapterCounterCoverage+'/'+value.summary.requests:'尚未运行。';
 $('report-warning').textContent=value?.error||value?.persistenceWarning||'';
 for(const kind of ['json','md']){$(kind).hidden=!value;if(value)$(kind).href='/desktop-diagnostics/api/export?cacheProbe='+encodeURIComponent(value.id)+'&format='+kind;}
}
async function history(){const selected=$('history').value;const items=await api('history');$('history').replaceChildren(new Option('当前探针',''),...items.map(r=>new Option(new Date(r.startedAt).toLocaleString()+' · '+(status[r.status]??r.status)+' · '+r.model,r.id)));if(items.some(r=>r.id===selected))$('history').value=selected;}
async function refresh(reset=false){if(polling)return;polling=true;const revision=mutation;try{const value=await api('state');if(revision!==mutation)return;config=value;current=value.current;
 if(!loaded||reset){const id=$('model').value;$('model').replaceChildren(...value.models.map(m=>new Option(m.name||m.id,m.id)));if(value.models.some(m=>m.id===id))$('model').value=id;capabilities();$('adapter').textContent='协议：'+value.adapter.api+'\n保留设置：'+value.adapter.retention+'\n标记：'+value.adapter.cacheControlFormat+'\n缓存键模式：'+({native:'原生兼容',off:'关闭',session:'按会话生成'}[value.adapter.cacheKeyMode]??'未知')+'\n已确认模型：'+(value.adapter.cacheKeyModels?.join('、')||'无')+'\n\n'+value.adapter.notes.join('\n');$('notice').textContent=value.warning||(value.models.length?'配置已载入。探针不会自动运行。':'请先在连接设置中保存并启动模型连接。');loaded=true;}
 if(formFingerprint!==value.fingerprint)$('notice').textContent='连接配置已经变化，请刷新配置后再保存或运行探针。';
 if(!$('history').value)report(current);
 const signature=(current?.id??'')+':'+(current?.status??'');if(signature!==lastStatus){lastStatus=signature;await history();}controls();
 }catch(error){$('notice').textContent=error.message;}finally{polling=false;}}
for(const [key,name] of Object.entries(names)){const label=text('label',name),select=document.createElement('select');select.id=key;select.append(new Option('未知','unknown'),new Option('支持（用户声明）','supported'),new Option('不支持（用户声明）','unsupported'));label.append(select);$('capabilities').append(label);}
$('model').onchange=()=>{$('accept').checked=false;capabilities();controls();};$('accept').onchange=controls;$('bytes').onchange=$('requests').onchange=()=>{$('accept').checked=false;budget();controls();};
$('save-capabilities').onclick=async()=>{busy=true;mutation++;controls();try{await api('capabilities',{model:$('model').value,fingerprint:formFingerprint,features:Object.fromEntries(Object.keys(names).map(k=>[k,$(k).value]))});await refresh(true);$('notice').textContent='声明已保存；没有修改请求参数。';}catch(error){$('notice').textContent=error.message;}finally{busy=false;controls();}};
$('start').onclick=async()=>{busy=true;mutation++;controls();try{current=await api('start',{model:$('model').value,fingerprint:formFingerprint,inputBytes:Number($('bytes').value),requests:Number($('requests').value),accepted:$('accept').checked});$('history').value='';$('accept').checked=false;report(current);$('notice').textContent='探针已开始，仅发送合成文本。';}catch(error){$('notice').textContent=error.message;}finally{busy=false;controls();}};
$('cancel').onclick=async()=>{busy=true;mutation++;controls();try{await api('cancel',{id:current.id});$('notice').textContent='已请求取消。已到达服务端的请求可能仍计费。';}catch(error){$('notice').textContent=error.message;}finally{busy=false;controls();}};
$('history').onchange=async()=>{try{report($('history').value?await api('report?id='+encodeURIComponent($('history').value)):current);}catch(error){$('notice').textContent=error.message;}};
$('refresh').onclick=()=>refresh(true);budget();refresh(true);setInterval(()=>{if(document.visibilityState!=='hidden')refresh();},1500);
`;
